### ISSUE TITLE
No longer working: can't build zfs-dkms for 5.13.1

### ISSUE THREAD

**Issue by DigiDr** [terem42/zfs-hetzner-vm#14]
Hiya,

See the following logs on a fresh system. Zfs can't be built against 5.13.1. Not sure what the fix is:

```Loading new zfs-2.0.3 DKMS files...
Building for 5.13.1
Building initial module for 5.13.1
configure: error:
	*** None of the expected "capability" interfaces were detected.
	*** This may be because your kernel version is newer than what is
	*** supported, or you are using a patched custom kernel with
	*** incompatible modifications.
	***
	*** ZFS Version: zfs-2.0.3-8~bpo10+1
	*** Compatible Kernels: 3.10 - 5.10

Error! Bad return status for module build on kernel: 5.13.1 (x86_64)```

[debian-log.txt](https://github.com/terem42/zfs-hetzner-vm/files/6810761/debian-log.txt)

**Comment by terem42** [comment]
it you really need newest kernel, use zfs-2.1.0 instead, it supports kernel 5.13, 
zfs-2.1.0 is not included in Debian repos, but it can be compiled from the source

**Comment by DigiDr** [comment]
@terem42 

The latest (default) rescue kernel loaded is 5.13, which means we cannot built the latest available buster-backports zfs-dkms (which only supports kernel to 5.12).

1. I've updated the script to compile from source, as you suggest. I did this manually but believe the changes should work within your script too.
2. I've also updated the entire script to use latest debian bullseye. This requires some changes to the repos but otherwise was very easy and i can confirm this is working.

Feel free to pull changes from my branch.

**Comment by freehussain** [comment]
hello,

still the issue exist

Loading new zfs-2.0.3 DKMS files...
Building for 5.13.1
Building initial module for 5.13.1
configure: error: 
	*** None of the expected "capability" interfaces were detected.
	*** This may be because your kernel version is newer than what is
	*** supported, or you are using a patched custom kernel with
	*** incompatible modifications.
	***
	*** ZFS Version: zfs-2.0.3-8~bpo10+1
	*** Compatible Kernels: 3.10 - 5.10
	
Error! Bad return status for module build on kernel: 5.13.1 (x86_64)
Consult /var/lib/dkms/zfs/2.0.3/build/make.log for more information.
dpkg: error processing package zfs-dkms (--configure):
 installed zfs-dkms package post-installation script subprocess returned error exit status 10
dpkg: dependency problems prevent configuration of zfs-zed:
 zfs-zed depends on zfs-modules | zfs-dkms; however:
  Package zfs-modules is not installed.
  Package zfs-dkms which provides zfs-modules is not configured yet.
  Package zfs-dkms is not configured yet.

dpkg: error processing package zfs-zed (--configure):
 dependency problems - leaving unconfigured
Processing triggers for initramfs-tools (0.133+deb10u1) ...
Errors were encountered while processing:
 zfs-dkms
 zfs-zed
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by DigiDr** [comment]
@freehussain try using the latest version in my fork.

**Comment by freehussain** [comment]
thank you @DigiDr

**Comment by DigiDr** [comment]
@freehussain hmm we probably only want to build and install _either_ the kmod _or_ the DKMS (not both). I've make a small modification, feel free to try again. I don't currently have a system to play with this on again myself.

**Comment by terem42** [comment]
I have latest version 2.1.0 from Openzfs compiled, tested and packed as Debian repo artefact. 
It supports kernel 5.13, you can use it, follow instructions here: https://terem42.github.io/zfs-debian/
The module is built using full test coverage on each build via Github Actions, you can fork it and have your own guthub hosted Debian repo, read more here: https://github.com/terem42/zfs-debian

**Comment by terem42** [comment]
I"ll make new script version for Debian 11, seems rescue system now has zfs install script available.

**Comment by terem42** [comment]
I#ve created new script for Debian 11, it uses new rescue console from Hetzner, works now
