### ISSUE TITLE
How do I select the disks?

### ISSUE THREAD

**Issue by thewebcapsule** [terem42/zfs-hetzner-vm#19]
Hello,

I would like to create pool with all the 4 disks that are on my server. However, I only see the labels with 1 disk while running the script. I'm not super experienced with Linux - could you guide me to documentation where I could know what disk to select?

When I selected the ones with the word "Samsung", the process completed and gave me a message of one or more disk was busy.

Disks Image: 
<img width="831" alt="Screenshot 2021-09-16 at 3 43 43 AM" src="https://user-images.githubusercontent.com/40489404/133517047-422bbfee-8330-4a63-aad7-30e46c51a9cd.png">

The partitions after running the script:

`root@rescue ~ # sudo fdisk -l
Disk /dev/ram0: 64 MiB, 67108864 bytes, 131072 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram1: 64 MiB, 67108864 bytes, 131072 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram2: 64 MiB, 67108864 bytes, 131072 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram3: 64 MiB, 67108864 bytes, 131072 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram4: 64 MiB, 67108864 bytes, 131072 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram5: 64 MiB, 67108864 bytes, 131072 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram6: 64 MiB, 67108864 bytes, 131072 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram7: 64 MiB, 67108864 bytes, 131072 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram8: 64 MiB, 67108864 bytes, 131072 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram9: 64 MiB, 67108864 bytes, 131072 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram10: 64 MiB, 67108864 bytes, 131072 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram11: 64 MiB, 67108864 bytes, 131072 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram12: 64 MiB, 67108864 bytes, 131072 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram13: 64 MiB, 67108864 bytes, 131072 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram14: 64 MiB, 67108864 bytes, 131072 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram15: 64 MiB, 67108864 bytes, 131072 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/loop0: 2.86 GiB, 3068773888 bytes, 5993699 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/nvme1n1: 3.49 TiB, 3840755982336 bytes, 7501476528 sectors
Disk model: SAMSUNG MZQL23T8HCLS-00A07              
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 131072 bytes / 131072 bytes
Disklabel type: gpt
Disk identifier: EDA7164D-C134-4A01-8C32-497F9068585F

Device           Start        End    Sectors  Size Type
/dev/nvme1n1p1      48       2047       2000 1000K BIOS boot
/dev/nvme1n1p2    2048    1050623    1048576  512M Solaris /usr & Apple ZFS
/dev/nvme1n1p3 1050624 7501476494 7500425871  3.5T Solaris /usr & Apple ZFS

Partition 1 does not start on physical sector boundary.

Disk /dev/nvme0n1: 3.49 TiB, 3840755982336 bytes, 7501476528 sectors
Disk model: SAMSUNG MZQL23T8HCLS-00A07              
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 131072 bytes / 131072 bytes
Disklabel type: gpt
Disk identifier: 661B0DE6-BF26-4B19-B0EE-A726058F9156

Device           Start        End    Sectors  Size Type
/dev/nvme0n1p1      48       2047       2000 1000K BIOS boot
/dev/nvme0n1p2    2048    1050623    1048576  512M Solaris /usr & Apple ZFS
/dev/nvme0n1p3 1050624 7501476494 7500425871  3.5T Solaris /usr & Apple ZFS

Partition 1 does not start on physical sector boundary.

Disk /dev/nvme3n1: 3.49 TiB, 3840755982336 bytes, 7501476528 sectors
Disk model: SAMSUNG MZQLB3T8HALS-00007              
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 4B5EFE90-8690-4A6A-904A-A0DDB34C58BC

Device           Start        End    Sectors  Size Type
/dev/nvme3n1p1      48       2047       2000 1000K BIOS boot
/dev/nvme3n1p2    2048    1050623    1048576  512M Solaris /usr & Apple ZFS
/dev/nvme3n1p3 1050624 7501476494 7500425871  3.5T Solaris /usr & Apple ZFS

Disk /dev/nvme2n1: 3.49 TiB, 3840755982336 bytes, 7501476528 sectors
Disk model: SAMSUNG MZQLB3T8HALS-00007              
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: F49A38F8-0590-412A-8350-33744554CB28

Device           Start        End    Sectors  Size Type
/dev/nvme2n1p1      48       2047       2000 1000K BIOS boot
/dev/nvme2n1p2    2048    1050623    1048576  512M Solaris /usr & Apple ZFS
/dev/nvme2n1p3 1050624 7501476494 7500425871  3.5T Solaris /usr & Apple ZFS

Disk /dev/md0: 15.98 GiB, 17162043392 bytes, 33519616 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 131072 bytes / 131072 bytes
`

Also, unable to SSH in after the installation was completed. 

Appreciate the script you've created. Thank you!

**Comment by terem42** [comment]
Normally all selected disks are used as a mirror. However, seems with new script version mirroring feature on boot pool no longer works correctly. ZFS pools are created normally, but the machine refuses to boot after install if mirroring setup was uses. Alternative would be to use mirroring for certain volumes only, but it precludes the ability to run machine with mirror setup right from the boot.

I'll look into it and will fix it.

**Comment by thewebcapsule** [comment]
I'm on Hetzner dedicated server. Sorry completely missed that this was for cloud!

**Comment by terem42** [comment]
technically you need just to update devices filtering in the script, or correctly pick up the right devices.
I do not have dedicated server on Hetzner, but I bet it wont be too hard.
Try to look for blocking devices using this simple oneliner:
````bash
 df | awk 'BEGIN {getline} {print $1}' | xargs -n 1 lsblk -no pkname
````
I've udated the boot sequence, now mirroring and dRAID properly works with new ZFS version.
