### ISSUE TITLE
need a hint how to unlock

### ISSUE THREAD

**Issue by jimi3** [terem42/zfs-hetzner-vm#22]
i do unlock my LUKS servers remotely but i am clueless how to do it with zfs on my new hetzner bare metal, could you enlighten me how to unlock zfs or are the Ubuntu scripts maybe broken?

end output output from install
`Setting up networkd-dispatcher (2.1-2~ubuntu20.04.1) ...
Setting up dropbear-initramfs (2019.78-2build1) ...
update-initramfs: deferring update (trigger activated)
Dropbear has been added to the initramfs. Don't forget to check
your "ip=" kernel bootparameter to match your desired initramfs
ip configuration.

Setting up systemd (245.4-4ubuntu3.13) ...
Installing new version of config file /etc/dhcp/dhclient-enter-hooks.d/resolved ...
Installing new version of config file /etc/systemd/resolved.conf ...
Setting up netplan.io (0.103-0ubuntu5~20.04.5) ...
Setting up systemd-timesyncd (245.4-4ubuntu3.13) ...
Setting up systemd-sysv (245.4-4ubuntu3.13) ...
Setting up ubuntu-minimal (1.450.2) ...
Setting up libnss-systemd:amd64 (245.4-4ubuntu3.13) ...
Setting up libpam-systemd:amd64 (245.4-4ubuntu3.13) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for plymouth-theme-ubuntu-text (0.9.4git20200323-0ubuntu6.2) ...
update-initramfs: deferring update (trigger activated)
Processing triggers for dbus (1.12.16-2ubuntu2.1) ...
Processing triggers for initramfs-tools (0.136ubuntu6.6) ...
update-initramfs: Generating /boot/initrd.img-5.4.0-91-generic
cryptsetup: ERROR: Couldn't resolve device rpool/ROOT/ubuntu
cryptsetup: WARNING: Couldn't determine root device
Processing triggers for ca-certificates (20210119~20.04.2) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
===========add static route to initramfs via hook to add default routes due to Ubuntu initramfs DHCP bug =========
======= update initramfs ==========
update-initramfs: Generating /boot/initrd.img-5.4.0-91-generic
cryptsetup: ERROR: Couldn't resolve device rpool/ROOT/ubuntu
cryptsetup: WARNING: Couldn't determine root device
======= update grub ==========
Sourcing file `/etc/default/grub'
Sourcing file `/etc/default/grub.d/init-select.cfg'
Generating grub configuration file ...
Warning: Failed to find a valid directory 'etc' for dataset 'rpool'. Ignoring
Warning: Ignoring rpool
Found linux image: vmlinuz-5.4.0-91-generic in rpool/ROOT/ubuntu
Found initrd image: initrd.img-5.4.0-91-generic in rpool/ROOT/ubuntu
done
======= setting up zed ==========
======= setting mountpoints ==========
========= add swap, if defined
======= unmounting filesystems and zfs pools ==========

###############################################################################
# unmount_and_export_fs
###############################################################################

Waiting for virtual filesystems to unmount 
===========exporting zfs pools=============
all zfs pools were succesfully exported
======== setup complete, rebooting ===============
root@rescue ~ # Connection to xxx.xxx.xxx.xxx closed by remote host.`

**Comment by terem42** [comment]
when you use encrypted zfs on root, upon detection of encrypted root, boot will stop boot, show command prompt and wait for you to type zfsunlock command. Once you run it, you will be prompted to enter the password. To ente rthe password ypu can use either KMS console or connect to the host remotely with SSH using root SSH key, copied from the resque console at the setup stage.

**Comment by jimi3** [comment]
Nice that worked, thanks.
If you would be so kind and help a bit further, i am struggling writing a similar script i have for remote unlocking my LUKS hosts and passing on the password for zfsunlock.
