### ISSUE TITLE
IPv4 configuration incorrect

### ISSUE THREAD

**Issue by schultmc** [terem42/zfs-hetzner-vm#25]
Reviewing the scripts it looks like DHCP is set for IPv4. After running the script, I'm unable to connect to my dedicated server over IPv4. I haven't yet tried connecting over IPv6 but the IPv4 setup seems incorrect. At least for dedicated servers I don't think Hetzner's running DHCP.

**Comment by schultmc** [comment]
I'm also unable to connect to my dedicated server via IPv6 after the script completes. I'm testing some hard coded, server specific changes locally as a workaround.

**Comment by terem42** [comment]
current settings assume using DHCP its more evident than installing additional package
