### ISSUE TITLE
default settings break root on zfs after kernel updates

### ISSUE THREAD

**Issue by lc-guy** [terem42/zfs-hetzner-vm#28]
See https://github.com/openzfs/zfs/issues/10355 . `REMAKE_INITRD='yes'` needs to be added to `/etc/dkms/zfs.conf` to prevent breakage upon kernel updates, making it impossible to boot.
Took a lot of time to debug and fix, annoying.

Also, the grub changes make it impossible to boot into hetzner's rescue mode, requiring a support ticket to change boot order and make it working again. Please fix this.

Unrelated, but there's a stray 18.04 variable in the script:

https://github.com/terem42/zfs-hetzner-vm/blob/c2bd03377dfb2f502ba058c5d9c54447026780e6/hetzner-ubuntu20-zfs-setup.sh#L682

**Comment by Rocco83** [comment]
> Also, the grub changes make it impossible to boot into hetzner's rescue mode, requiring a support ticket to change boot order and make it working again. Please fix this.

can you elaborate this point? on which OS have you experienced it?

**Comment by crpb** [comment]
I also just ran into the issue of a non-booting system (Debian Bullseye) after an upgrade of `linux-image-amd64`. Maybe this will keep the doctor(rescue-shell) away in the future.
