### ISSUE TITLE
zfs: command not found

### ISSUE THREAD

**Issue by majastro** [terem42/zfs-hetzner-vm#46]
No matter which version of script I try, it keeps failing here

checking whether inode_owner_or_capable() takes user_ns... configure: error: 
        *** None of the expected "capability" interfaces were detected.
        *** This may be because your kernel version is newer than what is
        *** supported, or you are using a patched custom kernel with
        *** incompatible modifications.
        ***
        *** ZFS Version: zfs-2.1.11-1
        *** Compatible Kernels: 3.10 - 6.2

Install failed, please fix manually!
bash: line 499: zfs: command not found

**Comment by KorewaKiyo** [comment]
This is an upstream issue with ZFS, with the rescue environment being based on kernel 6.3.1, these scripts won't work on it until the fix is available via APT repos,

It's marked closed on  openzfs/zfs/issues/14622, so just a waiting game

**Comment by eleaner** [comment]
I run into the same issue. I just bought 15x6TB server yesterday with the idea to run debian on ZFS

**Comment by KorewaKiyo** [comment]
I wasn't able to get it to work, But it seems you can manually install to a small ext4 partition and then copy the / to a zfs dataset

**Comment by eleaner** [comment]
I don't think i feel that savvy with linux

**Comment by KorewaKiyo** [comment]
> I don't think i feel that savvy with linux

You mentioned 15x6TB, do you have a disk to install the OS to as well, or is that your only disks?
If you have an SSD or such you can use for OS, you can install to that alone, and then install zfs-dkms when you're in your chosen distro.

All the distro versions this script helps with have a much lower default kernel than the Hetzner rescue image, so ZFS will have no issue installing on them.

**Comment by eleaner** [comment]
only the 15xHDD
it's an old/cheapish machine

I hoped that ZFS can protect also my boot and root
I assume I could sacrifice one HDD for system
I guess I could also do softraid on tiny portions of those 15HDD and use the rest as ZFS

**Comment by eleaner** [comment]
> > I don't think i feel that savvy with linux
> 
> You mentioned 15x6TB, do you have a disk to install the OS to as well, or is that your only disks? If you have an SSD or such you can use for OS, you can install to that alone, and then install zfs-dkms when you're in your chosen distro.
> 
> All the distro versions this script helps with have a much lower default kernel than the Hetzner rescue image, so ZFS will have no issue installing on them.

Wait, does it mean that would i request KVM and USB to boot wit linux recuse I could use the scripts?

**Comment by KorewaKiyo** [comment]
> > > I don't think i feel that savvy with linux
> > 
> > 
> > You mentioned 15x6TB, do you have a disk to install the OS to as well, or is that your only disks? If you have an SSD or such you can use for OS, you can install to that alone, and then install zfs-dkms when you're in your chosen distro.
> > All the distro versions this script helps with have a much lower default kernel than the Hetzner rescue image, so ZFS will have no issue installing on them.
> 
> Wait, does it mean that would i request KVM and USB to boot with linux recuse/live I could use the scripts?

If you installed to a USB or other single disk, you can then use an installed system to bootstrap another one, the rescue system still has a kernel that's too new

**Comment by KorewaKiyo** [comment]
Ignore my previous advice, I put in a support request for a KVM (free for 3 hours, which should be plenty.)

Use the KVM to live boot a *desktop* version of your chosen distro (I used Ubuntu 20.04), and you can use that + The very good, official ZoL docs to install from there. I used https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/Ubuntu%2020.04%20Root%20on%20ZFS.html but they also have docs for debian stretch-bullseye and ubuntu 18-22

**Comment by majastro** [comment]
Any update on whether this is fixed now?

**Comment by eleaner** [comment]
It was super easy to get KVM access from hetzner

**Comment by hhansen06** [comment]
in rescue, edit the sources line to trixie, install zfsutils-linux, edit the source line back before running the script.
