### ISSUE TITLE
`Ubuntu 22 LTS` script fails with `bullseye-backports is invalid`

### ISSUE THREAD

**Issue by Legless** [terem42/zfs-hetzner-vm#48]
Hello. 

Ubuntu 22 script fails during install with following:

```
Setting up python3-gi (3.38.0-2) ...
Setting up packagekit (1.2.2-2) ...
Created symlink /etc/systemd/user/sockets.target.wants/pk-debconf-helper.socket → /usr/lib/systemd/user/pk-debconf-helper.socket.
Setting up packagekit-tools (1.2.2-2) ...
Setting up software-properties-common (0.96.20.2-2.1) ...
Processing triggers for libc-bin (2.31-13+deb11u6) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for dbus (1.12.24-0+deb11u1) ...
gpg: key 871920D1991BC93C: public key "Ubuntu Archive Automatic Signing Key (2018) <ftpmaster@ubuntu.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
Reading package lists... Done
E: The value 'bullseye-backports' is invalid for APT::Default-Release as such a release is not available in the sources
```

Ubuntu 20 script is okay.

**Comment by cinderblock** [comment]
I added a fall back that seems to be working: https://github.com/cinderblock/zfs-hetzner-vm/commit/8e78e868866df127ac80e369571221f5ce4ffa90

**Comment by Legless** [comment]
Can't test for now (already set up v20), but thank you very much for your work. ♥

**Comment by adsharma** [comment]
Now it fails with:

```

**Comment by adsharma** [comment]
This was a ipv6 only instance FWIW. Was not able to connect to this [url](https://gist.githubusercontent.com/tijszwinkels/966ec9b38b190bf80c2b2e4cfddf252a/raw/6d42ae592a49deb141ed4c42e6973eec5f4247f8/zfs) to fetch zfs. I think I saw some "invalid hostname" errors when the script was running.

**Comment by adsharma** [comment]
Works fine with ipv4.

**Comment by cinderblock** [comment]
Yes. Many services still don't work on IPv6 only. It's surprising to me how many don't.

**Comment by IITuxtmuxII** [comment]
on my dedi box it still givbe me this error

**Comment by 42piratas** [comment]
I'm also facing the same error:

`E: The value 'bullseye-backports' is invalid for APT::Default-Release as such a release is not available in the sources`

**Comment by terem42** [comment]
updated script, now installs correctly
