### ISSUE TITLE
no connection after ubuntu script

### ISSUE THREAD

**Issue by s3uzz** [terem42/zfs-hetzner-vm#9]
======= setup OpenSSH  ==========
Creating SSH2 RSA key; this may take some time ...
2048 SHA256:5S2VVntYfZA+cVa1NPj/NbFm2lszVkrJXhb06fSdV68 root@rescue (RSA)
Creating SSH2 ECDSA key; this may take some time ...
256 SHA256:XExQhAQ2sIZ4sDFgdgaWEAJ7EEtauQyfrTfZfxLpBEc root@rescue (ECDSA)
Creating SSH2 ED25519 key; this may take some time ...
256 SHA256:nTPTa82V/v+PAZmAAkPYU/0tjBT9UfQ2XvZltr/DbDs root@rescue (ED25519)
Running in chroot, ignoring request.
======= set root password ==========

ssh: connect to host xxxx port 22: Connection refused

**Comment by terem42** [comment]
incorrect routes setup, fixes in new script for Ubuntu 20, will backport to script for Ubuntu 18

**Comment by terem42** [comment]
updated to new rescue, works now

**Comment by jlsjonas** [comment]
Seem to be getting `port 22: Operation timed out` now after the Ubuntu 20 script rebooted the system (waiting on KVM to do further investigations)
